/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppReportRouteImport } from './routes/app.report'
import { Route as AppPreviewRouteImport } from './routes/app.preview'
import { Route as AppIntakeRouteImport } from './routes/app.intake'
import { Route as AppFailuresRouteImport } from './routes/app.failures'
import { Route as AppDeploymentsRouteImport } from './routes/app.deployments'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppChangesRouteImport } from './routes/app.changes'
import { Route as AppAgentsRouteImport } from './routes/app.agents'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppPreviewRoute = AppPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AppRoute,
} as any)
const AppIntakeRoute = AppIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AppRoute,
} as any)
const AppFailuresRoute = AppFailuresRouteImport.update({
  id: '/failures',
  path: '/failures',
  getParentRoute: () => AppRoute,
} as any)
const AppDeploymentsRoute = AppDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppChangesRoute = AppChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/agents': typeof AppAgentsRoute
  '/app/changes': typeof AppChangesRoute
  '/app/chat': typeof AppChatRoute
  '/app/deployments': typeof AppDeploymentsRoute
  '/app/failures': typeof AppFailuresRoute
  '/app/intake': typeof AppIntakeRoute
  '/app/preview': typeof AppPreviewRoute
  '/app/report': typeof AppReportRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/changes': typeof AppChangesRoute
  '/app/chat': typeof AppChatRoute
  '/app/deployments': typeof AppDeploymentsRoute
  '/app/failures': typeof AppFailuresRoute
  '/app/intake': typeof AppIntakeRoute
  '/app/preview': typeof AppPreviewRoute
  '/app/report': typeof AppReportRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/agents': typeof AppAgentsRoute
  '/app/changes': typeof AppChangesRoute
  '/app/chat': typeof AppChatRoute
  '/app/deployments': typeof AppDeploymentsRoute
  '/app/failures': typeof AppFailuresRoute
  '/app/intake': typeof AppIntakeRoute
  '/app/preview': typeof AppPreviewRoute
  '/app/report': typeof AppReportRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/agents'
    | '/app/changes'
    | '/app/chat'
    | '/app/deployments'
    | '/app/failures'
    | '/app/intake'
    | '/app/preview'
    | '/app/report'
    | '/app/tasks'
    | '/app/team'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/agents'
    | '/app/changes'
    | '/app/chat'
    | '/app/deployments'
    | '/app/failures'
    | '/app/intake'
    | '/app/preview'
    | '/app/report'
    | '/app/tasks'
    | '/app/team'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/agents'
    | '/app/changes'
    | '/app/chat'
    | '/app/deployments'
    | '/app/failures'
    | '/app/intake'
    | '/app/preview'
    | '/app/report'
    | '/app/tasks'
    | '/app/team'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/report': {
      id: '/app/report'
      path: '/report'
      fullPath: '/app/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/preview': {
      id: '/app/preview'
      path: '/preview'
      fullPath: '/app/preview'
      preLoaderRoute: typeof AppPreviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/intake': {
      id: '/app/intake'
      path: '/intake'
      fullPath: '/app/intake'
      preLoaderRoute: typeof AppIntakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/failures': {
      id: '/app/failures'
      path: '/failures'
      fullPath: '/app/failures'
      preLoaderRoute: typeof AppFailuresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deployments': {
      id: '/app/deployments'
      path: '/deployments'
      fullPath: '/app/deployments'
      preLoaderRoute: typeof AppDeploymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/changes': {
      id: '/app/changes'
      path: '/changes'
      fullPath: '/app/changes'
      preLoaderRoute: typeof AppChangesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppChangesRoute: typeof AppChangesRoute
  AppChatRoute: typeof AppChatRoute
  AppDeploymentsRoute: typeof AppDeploymentsRoute
  AppFailuresRoute: typeof AppFailuresRoute
  AppIntakeRoute: typeof AppIntakeRoute
  AppPreviewRoute: typeof AppPreviewRoute
  AppReportRoute: typeof AppReportRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppChangesRoute: AppChangesRoute,
  AppChatRoute: AppChatRoute,
  AppDeploymentsRoute: AppDeploymentsRoute,
  AppFailuresRoute: AppFailuresRoute,
  AppIntakeRoute: AppIntakeRoute,
  AppPreviewRoute: AppPreviewRoute,
  AppReportRoute: AppReportRoute,
  AppTasksRoute: AppTasksRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
