/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoPreviewRouteImport } from './routes/demo-preview'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppSuggestedAppsRouteImport } from './routes/app.suggested-apps'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportRouteImport } from './routes/app.report'
import { Route as AppPreviewRouteImport } from './routes/app.preview'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppIntakeRouteImport } from './routes/app.intake'
import { Route as AppFailuresRouteImport } from './routes/app.failures'
import { Route as AppDiscoveriesRouteImport } from './routes/app.discoveries'
import { Route as AppDeploymentsRouteImport } from './routes/app.deployments'
import { Route as AppConnectRouteImport } from './routes/app.connect'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppChangesRouteImport } from './routes/app.changes'
import { Route as AppBranchesRouteImport } from './routes/app.branches'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppAgentsAgentIdRouteImport } from './routes/app.agents.$agentId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPreviewRoute = DemoPreviewRouteImport.update({
  id: '/demo-preview',
  path: '/demo-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSuggestedAppsRoute = AppSuggestedAppsRouteImport.update({
  id: '/suggested-apps',
  path: '/suggested-apps',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppPreviewRoute = AppPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppIntakeRoute = AppIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AppRoute,
} as any)
const AppFailuresRoute = AppFailuresRouteImport.update({
  id: '/failures',
  path: '/failures',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoveriesRoute = AppDiscoveriesRouteImport.update({
  id: '/discoveries',
  path: '/discoveries',
  getParentRoute: () => AppRoute,
} as any)
const AppDeploymentsRoute = AppDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppChangesRoute = AppChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AppAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo-preview': typeof DemoPreviewRoute
  '/login': typeof LoginRoute
  '/app/activity': typeof AppActivityRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/branches': typeof AppBranchesRoute
  '/app/changes': typeof AppChangesRoute
  '/app/chat': typeof AppChatRoute
  '/app/connect': typeof AppConnectRoute
  '/app/deployments': typeof AppDeploymentsRoute
  '/app/discoveries': typeof AppDiscoveriesRoute
  '/app/failures': typeof AppFailuresRoute
  '/app/intake': typeof AppIntakeRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/preview': typeof AppPreviewRoute
  '/app/report': typeof AppReportRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suggested-apps': typeof AppSuggestedAppsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
  '/app/agents/$agentId': typeof AppAgentsAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo-preview': typeof DemoPreviewRoute
  '/login': typeof LoginRoute
  '/app/activity': typeof AppActivityRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/branches': typeof AppBranchesRoute
  '/app/changes': typeof AppChangesRoute
  '/app/chat': typeof AppChatRoute
  '/app/connect': typeof AppConnectRoute
  '/app/deployments': typeof AppDeploymentsRoute
  '/app/discoveries': typeof AppDiscoveriesRoute
  '/app/failures': typeof AppFailuresRoute
  '/app/intake': typeof AppIntakeRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/preview': typeof AppPreviewRoute
  '/app/report': typeof AppReportRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suggested-apps': typeof AppSuggestedAppsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app': typeof AppIndexRoute
  '/app/agents/$agentId': typeof AppAgentsAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo-preview': typeof DemoPreviewRoute
  '/login': typeof LoginRoute
  '/app/activity': typeof AppActivityRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/branches': typeof AppBranchesRoute
  '/app/changes': typeof AppChangesRoute
  '/app/chat': typeof AppChatRoute
  '/app/connect': typeof AppConnectRoute
  '/app/deployments': typeof AppDeploymentsRoute
  '/app/discoveries': typeof AppDiscoveriesRoute
  '/app/failures': typeof AppFailuresRoute
  '/app/intake': typeof AppIntakeRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/preview': typeof AppPreviewRoute
  '/app/report': typeof AppReportRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suggested-apps': typeof AppSuggestedAppsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
  '/app/agents/$agentId': typeof AppAgentsAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo-preview'
    | '/login'
    | '/app/activity'
    | '/app/agents'
    | '/app/branches'
    | '/app/changes'
    | '/app/chat'
    | '/app/connect'
    | '/app/deployments'
    | '/app/discoveries'
    | '/app/failures'
    | '/app/intake'
    | '/app/notifications'
    | '/app/preview'
    | '/app/report'
    | '/app/settings'
    | '/app/suggested-apps'
    | '/app/tasks'
    | '/app/team'
    | '/app/'
    | '/app/agents/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo-preview'
    | '/login'
    | '/app/activity'
    | '/app/agents'
    | '/app/branches'
    | '/app/changes'
    | '/app/chat'
    | '/app/connect'
    | '/app/deployments'
    | '/app/discoveries'
    | '/app/failures'
    | '/app/intake'
    | '/app/notifications'
    | '/app/preview'
    | '/app/report'
    | '/app/settings'
    | '/app/suggested-apps'
    | '/app/tasks'
    | '/app/team'
    | '/app'
    | '/app/agents/$agentId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo-preview'
    | '/login'
    | '/app/activity'
    | '/app/agents'
    | '/app/branches'
    | '/app/changes'
    | '/app/chat'
    | '/app/connect'
    | '/app/deployments'
    | '/app/discoveries'
    | '/app/failures'
    | '/app/intake'
    | '/app/notifications'
    | '/app/preview'
    | '/app/report'
    | '/app/settings'
    | '/app/suggested-apps'
    | '/app/tasks'
    | '/app/team'
    | '/app/'
    | '/app/agents/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoPreviewRoute: typeof DemoPreviewRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-preview': {
      id: '/demo-preview'
      path: '/demo-preview'
      fullPath: '/demo-preview'
      preLoaderRoute: typeof DemoPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suggested-apps': {
      id: '/app/suggested-apps'
      path: '/suggested-apps'
      fullPath: '/app/suggested-apps'
      preLoaderRoute: typeof AppSuggestedAppsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/report': {
      id: '/app/report'
      path: '/report'
      fullPath: '/app/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/preview': {
      id: '/app/preview'
      path: '/preview'
      fullPath: '/app/preview'
      preLoaderRoute: typeof AppPreviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/intake': {
      id: '/app/intake'
      path: '/intake'
      fullPath: '/app/intake'
      preLoaderRoute: typeof AppIntakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/failures': {
      id: '/app/failures'
      path: '/failures'
      fullPath: '/app/failures'
      preLoaderRoute: typeof AppFailuresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discoveries': {
      id: '/app/discoveries'
      path: '/discoveries'
      fullPath: '/app/discoveries'
      preLoaderRoute: typeof AppDiscoveriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deployments': {
      id: '/app/deployments'
      path: '/deployments'
      fullPath: '/app/deployments'
      preLoaderRoute: typeof AppDeploymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connect': {
      id: '/app/connect'
      path: '/connect'
      fullPath: '/app/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/changes': {
      id: '/app/changes'
      path: '/changes'
      fullPath: '/app/changes'
      preLoaderRoute: typeof AppChangesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/branches': {
      id: '/app/branches'
      path: '/branches'
      fullPath: '/app/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents/$agentId': {
      id: '/app/agents/$agentId'
      path: '/$agentId'
      fullPath: '/app/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppAgentsRoute
    }
  }
}

interface AppAgentsRouteChildren {
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRoute
}

const AppAgentsRouteChildren: AppAgentsRouteChildren = {
  AppAgentsAgentIdRoute: AppAgentsAgentIdRoute,
}

const AppAgentsRouteWithChildren = AppAgentsRoute._addFileChildren(
  AppAgentsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAgentsRoute: typeof AppAgentsRouteWithChildren
  AppBranchesRoute: typeof AppBranchesRoute
  AppChangesRoute: typeof AppChangesRoute
  AppChatRoute: typeof AppChatRoute
  AppConnectRoute: typeof AppConnectRoute
  AppDeploymentsRoute: typeof AppDeploymentsRoute
  AppDiscoveriesRoute: typeof AppDiscoveriesRoute
  AppFailuresRoute: typeof AppFailuresRoute
  AppIntakeRoute: typeof AppIntakeRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPreviewRoute: typeof AppPreviewRoute
  AppReportRoute: typeof AppReportRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuggestedAppsRoute: typeof AppSuggestedAppsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAgentsRoute: AppAgentsRouteWithChildren,
  AppBranchesRoute: AppBranchesRoute,
  AppChangesRoute: AppChangesRoute,
  AppChatRoute: AppChatRoute,
  AppConnectRoute: AppConnectRoute,
  AppDeploymentsRoute: AppDeploymentsRoute,
  AppDiscoveriesRoute: AppDiscoveriesRoute,
  AppFailuresRoute: AppFailuresRoute,
  AppIntakeRoute: AppIntakeRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPreviewRoute: AppPreviewRoute,
  AppReportRoute: AppReportRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuggestedAppsRoute: AppSuggestedAppsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoPreviewRoute: DemoPreviewRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
